### ISSUE TITLE
Stuck waiting for StS to generate log file

### ISSUE THREAD

**Issue by Zerazar** [karakasis/STS_AutoRoute#1]
I've followed the readme instructions and find myself stuck at waiting for StS to generate log file.

**Comment by karakasis** [comment]
I haven't checked the game in a while, it is possible that they changed the way they manage logs. 
If that's not the case though, make sure to close your game after going past Neoh and the open it back after a couple of seconds. It should work if you recreate that.

**Comment by karakasis** [comment]
Ah, it seems that the log folder has changed for me in the beta. I dont know about core game, but if you are in beta look for

[  In your root folder of the game SendToDevs > logs > SlayTheSpire.log  ]

Not only that, the log issue has been fixed apparently so you will not have to wait for the log, it will be instant no restarts needed :) I'll update the repository in the weekend ! 

Make sure to delete your log.txt so that you can re select the .log and you are golden! Have fun, and let me know how it went.

**Comment by Zerazar** [comment]
This is great, I really like it.

Is there a way I can use custom weights? It would be cool to be able to
just enter the weights I wanted the algorithm to use.

**Comment by karakasis** [comment]
Yeah i can add this functionality. Just didnt want to make it too complicated to use.

**Comment by Zerazar** [comment]
That would be really cool.
